// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8cGbqRxBqDHLl8VK3VoPNUKuJ3RVHHmA',
    appId: '1:320807342604:web:ad57bc544e010194219429',
    messagingSenderId: '320807342604',
    projectId: 'food-catalogs-86086',
    authDomain: 'food-catalogs-86086.firebaseapp.com',
    storageBucket: 'food-catalogs-86086.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4UOuGBQ2FeA4XEfPnx-TnIplTn87RVc',
    appId: '1:320807342604:android:d5b9ec68337faf84219429',
    messagingSenderId: '320807342604',
    projectId: 'food-catalogs-86086',
    storageBucket: 'food-catalogs-86086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBspbFeL2KSBNJY2p6wNfvq8wgyUIgfQdA',
    appId: '1:320807342604:ios:aab722f3230f0088219429',
    messagingSenderId: '320807342604',
    projectId: 'food-catalogs-86086',
    storageBucket: 'food-catalogs-86086.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBspbFeL2KSBNJY2p6wNfvq8wgyUIgfQdA',
    appId: '1:320807342604:ios:aab722f3230f0088219429',
    messagingSenderId: '320807342604',
    projectId: 'food-catalogs-86086',
    storageBucket: 'food-catalogs-86086.appspot.com',
    iosBundleId: 'com.example.flutterApplicationAuth',
  );
}
